name: benchmark

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ ! cancelled() }}
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt remove '~i ~nclang-tidy' -y
        sudo apt install --no-install-recommends -y \
                           autoconf \
                           autoconf-archive \
                           automake \
                           autopoint \
                           bison \
                           build-essential \
                           ca-certificates \
                           cmake \
                           cpio \
                           curl \
                           doxygen \
                           fakeroot \
                           flex \
                           gawk \
                           gettext \
                           git \
                           gperf \
                           help2man \
                           kmod \
                           libblkid-dev \
                           libc-ares-dev \
                           libcurl4-openssl-dev \
                           libdevmapper-dev \
                           libev-dev \
                           libevent-dev \
                           libexif-dev \
                           libflac-dev \
                           libgmp3-dev \
                           libid3tag0-dev \
                           libjpeg-dev \
                           libkeyutils-dev \
                           libltdl-dev \
                           libmpc-dev \
                           libmpfr-dev \
                           libncurses5-dev \
                           libogg-dev \
                           libsqlite3-dev \
                           libssl-dev \
                           libtool \
                           libtool-bin \
                           libudev-dev \
                           libvorbis-dev \
                           libxml2-dev \
                           locales \
                           pkg-config \
                           ppp-dev \
                           python3 \
                           python3-docutils \
                           texinfo \
                           unzip \
                           uuid \
                           uuid-dev \
                           vim \
                           wget \
                           xxd \
                           zlib1g-dev \
                           zstd

