name: benchmark

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ ! cancelled() }}
    steps:
    - run: |
        wget -qO- https://github.com/shvchk/gh-workflow-test/raw/main/benchmark.sh | bash

