name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v4

    - run: set -x
    - run: echo start

    - name: Prepare artifacts
      run: |
        date > date.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test
        retention-days: 1
        path: date.txt

    - run: echo wow

    - run: exit 1

    - run: echo finish
