name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v4

    - run: set -x
    - run: echo start

    - name: Run custom pre-build script
      run: '[[ -f pre-build.sh ]] && . pre-build.sh'

    - run: echo finish
