name: test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v4

    - run: |
        . <(cat variables build.config)

        for v in "${!PADAVAN_@}"; do
          echo "$v=${!v}"
        done

        for v in "${!CONFIG_@}"; do
          echo "$v=${!v}"
        done


    - run: |
        echo "$VAR3"
        echo "$VAR4"
        echo "$CONFIG_VENDOR"
        echo "$CONFIG_FIRMWARE_PRODUCT_ID"
        mkdir x
        cd $_
        date > d

    - run: echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d-%H.%M.%S')" >> $GITHUB_ENV

    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: ${{ env.CONFIG_VENDOR }}_${{ env.CONFIG_FIRMWARE_PRODUCT_ID }}
    #    path: |
    #      x/d
    #      build.config
    #    retention-days: 5

    #- name: Upload Release
    #  uses: softprops/action-gh-release@v1
    #  with:
    #    tag_name: ${{ env.BUILD_TIMESTAMP }}
    #    files: |
    #      x/d

