name: test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v4

    - run: |
        while read -r line || [[ -n "$line" ]]; do
          echo "$line" >> $GITHUB_ENV
        done < variables
    
    - run: |
        echo "$VAR3"
        mkdir x
        cd $_
        date > d
        pwd

    - run: pwd

    - run: echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.BUILD_TIMESTAMP }}
        files: |
          x/d

