name: test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v4

    - run: |
        while read -r line || [[ -n "$line" ]]; do
          echo "$line" >> $GITHUB_ENV
        done <<(cat variables build.config)
    
    - run: |
        echo "$VAR3"
        echo "$VAR4"
        echo "$CONFIG_VENDOR"
        echo "$CONFIG_FIRMWARE_PRODUCT_ID"
        mkdir x
        cd $_
        date > d

    - run: echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d-%H.%M.%S')" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.BUILD_TIMESTAMP }}
        files: |
          x/d

