name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      VAR1: test
      VAR2: ${{ env.VAR1 }}-lol
    steps:
    - uses: actions/checkout@v4

    - run: '[[ -f custom.sh ]] && . custom.sh'
    - run: '[[ -f custom2.sh ]] && . custom2.sh'

    - run: echo "LANG = $LANG | LC_ALL = $LC_ALL"

    - run: |
        VAR8=kek
        export VAR9=lol
    
    - run: |
        echo "$VAR1 $VAR2 $VAR3 $VAR8 $VAR9"
        mkdir x
        cd $_
        date > d

    - run: echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.BUILD_TIMESTAMP }}-${{ env.VAR8 }}-${{ env.VAR9 }}
        files: |
          /x
