name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
#    - uses: actions/checkout@v4

    - run: set -x
    - run: echo start

    - run: |
        PADAVAN_THEMES=(
        #  blue
        #  blue2
        #  grey
        #  grey2
        #  white
        #  yellow
        )

        for v in "${!PADAVAN_@}" "${!CONFIG_@}"; do
          echo "${!v}"
        done

        if (( ${#PADAVAN_THEMES[@]} )); then

          echo ${#PADAVAN_THEMES[@]}
          echo "${PADAVAN_THEMES[@]}"

        fi
        echo "TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV
        echo $TIMESTAMP

    - run: echo $TIMESTAMP
    - run: echo finish
