name: test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      VAR1: test
      VAR2: lol
    steps:
    - uses: actions/checkout@v4

    - run: echo hello world
